version: "3.9"
services:
  api:
    image: ghcr.io/sn0tten/markle/api:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT:-5432}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
    ports:
      - "3001:3001"

  web:
    image: ghcr.io/sn0tten/markle/web:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"
    depends_on:
      - api


